# for built-in resolvers
# see https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html#built-in-resolvers
data:
  cache_dir: ${oc.env:PWD}/data

checkpoints:
  cache_dir: ${oc.env:PWD}/checkpoints

logs:
  experiments: ${oc.env:PWD}/logs/experiments
  profiler: ${oc.env:PWD}/logs/profiler

logger:
  project: slm-evals

model:
  org: jxtngx
  name: Llama-3.2-3B-Instruct-Q4_K_M-GGUF

seed: 42